name: dkstore
description: "Belanja Kebutuhan Harian, Tanpa Ribet!"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.16+24

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^16.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  fluttertoast: ^8.2.12
  intl_phone_field: ^3.2.0
  hive_flutter: ^1.1.0
  flutter_styled_toast: ^2.2.1
  animated_hint_textfield: ^1.0.3
  heroicons_flutter: ^0.4.0
  google_maps_flutter: ^2.10.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  flutter_tabler_icons: ^1.43.0
  google_places_flutter: ^2.0.6
  change_app_package_name: ^1.5.0
  shimmer: ^3.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  remixicon: ^1.4.1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  flutter_html: ^3.0.0
  animations: ^2.0.11
  circular_gradient_spinner: ^0.0.3
  confetti: ^0.8.0
  image_picker: ^1.2.0
  razorpay_flutter: ^1.3.7
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  file_saver: ^0.3.1
  url_launcher: ^6.3.2
  flutter_stripe: ^12.1.1
  pay_with_paystack: ^1.0.14
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  firebase_auth: ^6.1.1
  flutter_local_notifications: ^19.5.0
  google_sign_in: ^7.2.0
  connectivity_plus: ^7.0.0
  speech_to_text: ^7.3.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.2
  photo_view: ^0.15.0
  youtube_player_flutter: ^9.1.3
  video_player: ^2.10.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  http: ^1.6.0
  sign_in_with_apple: ^7.0.1
  fast_cached_network_image: ^1.3.3+5
  webview_flutter: ^4.13.0
  file_picker: ^10.3.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/payment-logos/
    - assets/images/wallet/
    - assets/images/app_logos/
    - assets/images/empty-states/
    - assets/animations/

  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/Lexend_Deca/static/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend_Deca/static/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend_Deca/static/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend_Deca/static/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend_Deca/static/LexendDeca-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend_Deca/static/LexendDeca-ExtraBold.ttf
          weight: 800
